In [2]:
#Import the appropriate libraries 
import pandas as pd
import matplotlib.pyplot as mp

In [3]:
#Import the datetime module
from datetime import datetime

In [10]:
df = pd.read_excel(r"C:\Users\zholl\OneDrive\Documents\AR Aging.xlsx")

In [14]:
df.head(300)

,invoice_id,customer_id,invoice_date,due_date,invoice_amount,amount_paid,payment_date,status,currency,source_system
0,INV-1001,CUST-30,2024-08-19,2024-10-18,4009.72,4009.72,2024-10-06,Paid,USD,SAP
1,INV-1002,CUST-35,2024-09-30,2024-11-29,11363.62,0.00,NaT,Open,GBP,QuickBooks
2,INV-1003,CUST-19,2024-01-16,2024-03-01,40416.46,0.00,NaT,Open,GBP,SAP
3,INV-1004,CUST-22,2024-02-09,2024-03-25,36931.82,11970.07,2024-03-29,Partial,GBP,NetSuite
4,INV-1005,CUST-20,2024-01-06,2024-03-06,17123.08,0.00,NaT,Open,EUR,Oracle
...,...,...,...,...,...,...,...,...,...,...
295,INV-1296,CUST-45,2024-05-17,2024-07-16,46210.83,12603.04,2024-07-22,Partial,USD,QuickBooks
296,INV-1297,CUST-17,2024-12-24,2025-02-22,25661.31,5605.78,2025-03-03,Partial,GBP,SAP
297,INV-1298,CUST-47,2024-05-12,2024-07-11,31830.67,31830.67,2024-07-11,Paid,USD,SAP
298,INV-1299,CUST-18,2024-01-09,2024-03-09,41029.96,0.00,NaT,Open,EUR,NetSuite
299,INV-1300,CUST-26,2024-06-18,2024-08-02,46004.04,46004.04,2024-07-18,Paid,GBP,QuickBooks

In [12]:
#Examine the data types
df.dtypes

invoice_id                object
customer_id               object
invoice_date      datetime64[ns]
due_date          datetime64[ns]
invoice_amount           float64
amount_paid              float64
payment_date      datetime64[ns]
status                    object
currency                  object
source_system             object
dtype: object

In [51]:
#Let's add some more insights to this dataset 

#Calculate the amount due for open accounts
df['open_amount_due'] = df['invoice_amount'] - df['amount_paid'] 
#df_open = df[df['status'] == 'Open']

from datetime import date
#Define the date for this analysis. Let's use Jan 1, 2025 as the date due to the data ranges coming from 2024 and 2025
today = pd.Timestamp('2025-01-01')

#Calculate the days past due for open accounts
df['days_past_due'] = (today - df_open['due_date']).dt.days
#df_open['days_past_due'] = (today - df_open['due_date']).dt.days

#Create the bins and labels for the Age_bucket column 
bins = [-float('inf'), 0, 30, 60, 90, 180, 365, float('inf')]
labels = ['Current', '1-30 days', '31-60 days', '61-90 days', '91-180 days', '181-365 days', '365+ days']
df['age_bucket'] = pd.cut(df['days_past_due'], bins=bins, labels = labels)

In [53]:
df.head(300)
#df_open.head(5)

,invoice_id,customer_id,invoice_date,due_date,invoice_amount,amount_paid,payment_date,status,currency,source_system,open_amount_due,days_past_due,age_bucket
0,INV-1001,CUST-30,2024-08-19,2024-10-18,4009.72,4009.72,2024-10-06,Paid,USD,SAP,0.00,NaN,NaN
1,INV-1002,CUST-35,2024-09-30,2024-11-29,11363.62,0.00,NaT,Open,GBP,QuickBooks,11363.62,33.0,31-60 days
2,INV-1003,CUST-19,2024-01-16,2024-03-01,40416.46,0.00,NaT,Open,GBP,SAP,40416.46,306.0,181-365 days
3,INV-1004,CUST-22,2024-02-09,2024-03-25,36931.82,11970.07,2024-03-29,Partial,GBP,NetSuite,24961.75,NaN,NaN
4,INV-1005,CUST-20,2024-01-06,2024-03-06,17123.08,0.00,NaT,Open,EUR,Oracle,17123.08,301.0,181-365 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,INV-1296,CUST-45,2024-05-17,2024-07-16,46210.83,12603.04,2024-07-22,Partial,USD,QuickBooks,33607.79,NaN,NaN
296,INV-1297,CUST-17,2024-12-24,2025-02-22,25661.31,5605.78,2025-03-03,Partial,GBP,SAP,20055.53,NaN,NaN
297,INV-1298,CUST-47,2024-05-12,2024-07-11,31830.67,31830.67,2024-07-11,Paid,USD,SAP,0.00,NaN,NaN
298,INV-1299,CUST-18,2024-01-09,2024-03-09,41029.96,0.00,NaT,Open,EUR,NetSuite,41029.96,298.0,181-365 days
299,INV-1300,CUST-26,2024-06-18,2024-08-02,46004.04,46004.04,2024-07-18,Paid,GBP,QuickBooks,0.00,NaN,NaN

In [56]:
#Fix the NaN values in the 'days_past_due' & 'age_bucket' column
df['days_past_due']= df['days_past_due'].fillna(0)
df['age_bucket'] = df['age_bucket'].cat.add_categories('0').fillna('0')

In [68]:
#check the data frame
df.head(10)

,invoice_id,customer_id,invoice_date,due_date,invoice_amount,amount_paid,payment_date,status,currency,source_system,open_amount_due,days_past_due,age_bucket
0,INV-1001,CUST-30,2024-08-19,2024-10-18,4009.72,4009.72,2024-10-06,Paid,USD,SAP,0.00,0,0
1,INV-1002,CUST-35,2024-09-30,2024-11-29,11363.62,0.00,NaT,Open,GBP,QuickBooks,11363.62,33,31-60 days
2,INV-1003,CUST-19,2024-01-16,2024-03-01,40416.46,0.00,NaT,Open,GBP,SAP,40416.46,306,181-365 days
3,INV-1004,CUST-22,2024-02-09,2024-03-25,36931.82,11970.07,2024-03-29,Partial,GBP,NetSuite,24961.75,0,0
4,INV-1005,CUST-20,2024-01-06,2024-03-06,17123.08,0.00,NaT,Open,EUR,Oracle,17123.08,301,181-365 days
5,INV-1006,CUST-43,2024-09-13,2024-10-28,27754.95,0.00,NaT,Open,EUR,QuickBooks,27754.95,65,61-90 days
6,INV-1007,CUST-26,2024-03-21,2024-05-20,45850.84,0.00,NaT,Open,USD,QuickBooks,45850.84,226,181-365 days
7,INV-1008,CUST-45,2024-08-18,2024-10-02,2151.80,2151.80,2024-09-17,Paid,EUR,NetSuite,0.00,0,0
8,INV-1009,CUST-25,2024-06-06,2024-08-05,15252.56,0.00,NaT,Open,GBP,QuickBooks,15252.56,149,91-180 days
9,INV-1010,CUST-26,2024-07-11,2024-09-09,25415.36,25415.36,2024-08-31,Paid,GBP,SAP,0.00,0,0

In [58]:
df.dtypes

invoice_id                 object
customer_id                object
invoice_date       datetime64[ns]
due_date           datetime64[ns]
invoice_amount            float64
amount_paid               float64
payment_date       datetime64[ns]
status                     object
currency                   object
source_system              object
open_amount_due           float64
days_past_due             float64
age_bucket               category
dtype: object

In [60]:
#convert 'days_past_due' to a whole number. no decimals
df['days_past_due'] = df['days_past_due'].round().astype('int64')

In [62]:
df.dtypes
df.head(5)

,invoice_id,customer_id,invoice_date,due_date,invoice_amount,amount_paid,payment_date,status,currency,source_system,open_amount_due,days_past_due,age_bucket
0,INV-1001,CUST-30,2024-08-19,2024-10-18,4009.72,4009.72,2024-10-06,Paid,USD,SAP,0.00,0,0
1,INV-1002,CUST-35,2024-09-30,2024-11-29,11363.62,0.00,NaT,Open,GBP,QuickBooks,11363.62,33,31-60 days
2,INV-1003,CUST-19,2024-01-16,2024-03-01,40416.46,0.00,NaT,Open,GBP,SAP,40416.46,306,181-365 days
3,INV-1004,CUST-22,2024-02-09,2024-03-25,36931.82,11970.07,2024-03-29,Partial,GBP,NetSuite,24961.75,0,0
4,INV-1005,CUST-20,2024-01-06,2024-03-06,17123.08,0.00,NaT,Open,EUR,Oracle,17123.08,301,181-365 days

In [71]:
#convert all the data columns from datetime to date
df['invoice_date'] = df['invoice_date'].dt.date
df['due_date'] = df['due_date'].dt.date
df['payment_date'] = df['payment_date'].dt.date

In [73]:
df.dtypes

invoice_id           object
customer_id          object
invoice_date         object
due_date             object
invoice_amount      float64
amount_paid         float64
payment_date         object
status               object
currency             object
source_system        object
open_amount_due     float64
days_past_due         int64
age_bucket         category
dtype: object

In [75]:
#I mistakenly thought the dtype would say 'date', so let's convert it back to 'datetime'
df['invoice_date'] = pd.to_datetime(df['invoice_date'])
df['due_date'] = pd.to_datetime(df['due_date'])
df['payment_date'] = pd.to_datetime(df['payment_date'])

In [76]:
df.dtypes

invoice_id                 object
customer_id                object
invoice_date       datetime64[ns]
due_date           datetime64[ns]
invoice_amount            float64
amount_paid               float64
payment_date       datetime64[ns]
status                     object
currency                   object
source_system              object
open_amount_due           float64
days_past_due               int64
age_bucket               category
dtype: object

In [81]:
#Import the appropriate libraries: It's time to move the dataset to the ARAgingDB Database in SQL Server
import sqlalchemy as sal
from sqlalchemy import create_engine
import urllib

params = urllib.parse.quote_plus(
    "Driver={ODBC Driver 17 for SQL Server};"
    "Server=localhost;"
    "Database=ARAgingDB;"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [82]:
conn = engine.connect()
df.to_sql('AR_Aging',con=conn,index=False,if_exists='replace')

C:\Users\zholl\AppData\Local\Temp\ipykernel_10352\874022217.py:1: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  conn = engine.connect()

139

In [ ]:
#The dataframe has sucessfully been moved to the SQL Server!!!